---
- hosts: pddrserver
  remote_user: root
  become: yes
  tasks:
    - name: Install httpd on RedHat-based systems
      yum:
        name: httpd
        state: installed
      when: ansible_os_family == "RedHat"

    - name: Install apache2 on Debian-based systems
      apt:
        name: apache2
        state: installed
      when: ansible_os_family == "Debian"

    - name: Create index.html
      copy:
        src: index.html
        dest: /var/www/html

    - name: Start the httpd service (RedHat-based)
      service:
        name: httpd
        state: started
      when: ansible_os_family == "RedHat"

    - name: Start the apache2 service (Debian-based)
      service:
        name: apache2
        state: started
      when: ansible_os_family == "Debian"
