---
- hosts: pddrserver
  remote_user: root
  become: yes
  vars_files: 
    - abc.yml

  tasks:
    - name: Install package
      yum:
        name: "{{ pkg }}"
        state: installed

    - name: Copy index.html
      copy:
        src: index.html
        dest: /var/www/html

    - name: Start service
      service:
        name: "{{ pkg }}"
        state: started
