---
- hosts: pddrserver
  remote_user: root
  become: yes
  vars_prompt:
      -name: pkg
       prompt: enter package name
       private: no
    tasks:
     - name: pddr install httpd
       yum: name={{pkg}} state=installed
     - name: copy index.html
       copy: scr=index.html dest=/var/www/html
     - name: service httpd start
       service: name={{pkg}} state=started