---
- hosts: pddrserver
  remote_user: root
  become: yes
  tasks:
    - name: Installing multiple packages
      yum:
        name: "{{ item }}"
        state: installed
      with_items:
        - httpd
        - curl
        - wget
